### ISSUE TITLE
Help for a noobie

### ISSUE THREAD

**Issue by amateosos** [hmarsolla/telegram-bot-get-ip#1]
Hi, I am new to this, could you explain a bit more how to set up this proyect?

**Comment by odoooooo** [comment]
Hi,
try this:

~~~~
git clone https://github.com/hmarsolla/telegram-bot-get-ip.git
cd telegram-bot-get-ip
pip install -r requirements.txt
~~~~

Create a telegram bot and add the bot token and chat id to the config.py.
Finally start the bot script with `python my_ip_please.py`.

**Comment by hmarsolla** [comment]
@amateosos I'm sorry for the long delay. I've been a little bit away, but now I'm back. If you need anything be free to contact me, I'll do my best to help!
@odoooooo Thanks for the help, I also just merged your pull request, thank you a lot!!!

**Comment by hmarsolla** [comment]
I'll leave this issue open for awhile just in case. :)

**Comment by RonPimplebut** [comment]
Is there a way to run this on ARM like RaspberryPi4B?

Thanks in advance for your reply

**Comment by odoooooo** [comment]
Yes, should be, because it is only python code.

Do you have problems?
